### PR TITLE
feat: introduce a json schema file for yamlfmt

### PR DESCRIPTION
**Pull request by thiagowfx**
Docs:
- https://github.com/google/yamlfmt/blob/main/docs/config-file.md
- https://json-schema.org/
- https://json-schema.org/learn/getting-started-step-by-step#create-a-schema-definition

Issue #181

### CODE REVIEW

**Review by braydonk — APPROVED** [review]
Looks good to me! Thank you for adding this!

**Comment by thiagowfx** [comment]
After this is merged, the follow up is to add it to https://schemastore.org/. I am happy to do it as well once I have time.

**Comment by braydonk** [comment]
I do not know anything about JSON Schema, so if you know what needs to happen please go ahead. :smile:

**Comment by ccoVeille** [comment]
Don't be so happy. Now, you will have to maintain it 😬😅😂

Maybe, you should add a CI step to validate yamlfmt files against this schema

**Comment by braydonk** [comment]
Well if we're being specific, I don't *have* to maintain it. But as with anything that makes it to the repo I will try my best to keep it correct and up to date. In general if I add any new configuration values I will try to keep the schema up to date, and have any community contributions that add fields do the same.  
CI step would be a good idea, as would be adding fields for the `basic` formatter config values, as would be simply generating this schema directly from code instead of this being manual. I will not personally be putting any time in for improvements and stuff like that as I can't dedicate any, but I'll do my best to at least not break what is here now.

**Comment by ccoVeille** [comment]
I appreciate your message, it's clear. Thanks

**Comment by thiagowfx** [comment]
Indeed. Don't feel any obligation to maintain it, but it should be relatively easy to add new entries should new config keys be added. Feel free to add me as a reviewer if you would like.

The CI idea is also good. I don't want to promise because my time is also limited, but if I get spare cycles I'll look into it as well. :)

**Pull request merged**
