### PR TITLE
multilinediff: add multilinediff package

### PR DESCRIPTION
**Pull request by braydonk**
Just copy and pasting the stuff from the external multilinediff package to make it easier to deal with dependency breakages when they happen.

### CODE REVIEW

**Comment by ccoVeille** [comment]
I cannot understand how this lib was added to yamlfmt at first.

I mean the repository multilinediff had no star before I stared it.

**Comment by ccoVeille** [comment]
Here is the URL for lazy people https://github.com/RageCage64/multilinediff

**Comment by braydonk** [comment]
That is my personal GitHub account. I had written it in my spare time, but it ended up being useful so I imported it here.

**Comment by ccoVeille** [comment]
OK I get it here now, make sense. Thanks for replying me.

**Pull request merged**
