### PR TITLE
Update paths.md: fix typo

### PR DESCRIPTION
**Pull request by corneliusroemer**

### CODE REVIEW

**Comment by braydonk** [comment]
If you are willing to fill out the CLA I will merge this, if you're not interested in that I can make the fix myself. I appreciate the PR thanks for catching this!

**Comment by corneliusroemer** [comment]
@braydonk I've already filled out the CLA - somehow the bot didn't reply again after I did but you can see the CI :)

image

**Comment by braydonk** [comment]
Ah sorry, I didn't notice that since it doesn't show up in the maintainer "approve and run CI" view :sweat_smile: 

Thank you!

**Review by braydonk — APPROVED** [review]

**Comment by corneliusroemer** [comment]
>Ah sorry, I didn't notice that since it doesn't show up in the maintainer "approve and run CI" view 😅

Begging for an issue to be filed somewhere 😜

**Comment by braydonk** [comment]
Should have taken a screenshot while I had it! Not the first time I've been made the same mistake with that UX though, I'll catch it next time

**Comment by corneliusroemer** [comment]
To be fair to whoever wrote that cla bot, it does mention that at the bottom, though easily missed:
> For the most up to date status, view the checks section at the bottom of the pull request.

**Pull request merged**
