### PR TITLE
docs: fix typo comment

### PR DESCRIPTION
**Pull request by koki-develop**
It may not be something worth going out of your way to correct, but...

### CODE REVIEW

**Comment by braydonk** [comment]
Thanks! I can merge this if you're willing to sign the CLA, but if you don't want to you can close the PR and I'll get it another time.

**Comment by koki-develop** [comment]
@braydonk 

I signed it.
https://github.com/google/yamlfmt/pull/113/checks?check_run_id=13330743560

**Comment by braydonk** [comment]
Oops sorry, I got confused by the Actions UI.

**Review by braydonk — APPROVED** [review]
Thank you for the fix!

**Pull request merged**
